### PR TITLE
feat: adding websocket support + fixes for reblogs and favourites

### LINKED ISSUE #29: Add WebSocket transport for Mastodon streaming API
## Summary

The Mastodon streaming API supports two transports: **Server-Sent Events (SSE)** and **WebSockets**. Monstera currently implements only SSE. Some clients (e.g. Tusky, certain web clients) use the WebSocket transport, so we need to add support for it.

## Background

The Mastodon WebSocket API uses a single multiplexed endpoint:

```
GET /api/v1/streaming?access_token=TOKEN&stream=user
```

When the server detects an `Upgrade: websocket` header, it upgrades the connection instead of responding with SSE. Multiple streams can be subscribed/unsubscribed over a single WebSocket connection via JSON messages:

```json
{"type": "subscribe", "stream": "user"}
{"type": "subscribe", "stream": "hashtag", "tag": "golang"}
{"type": "unsubscribe", "stream": "hashtag", "tag": "golang"}
```

Server→client messages use this format:

```json
{"stream": ["user"], "event": "update", "payload": "{...}"}
{"stream": ["hashtag", "golang"], "event": "update", "payload": "{...}"}
```

## Current architecture

The SSE implementation has a clean separation that should make this straightforward:

- **Hub** (`internal/api/mastodon/sse/hub.go`) — manages client subscriptions with on-demand NATS core subscriptions and ref-counted fan-out. Already exposes a `Subscribe(streamKey) -> (chan SSEEvent, cancel)` interface.
- **Subscriber** (`internal/api/mastodon/sse/subscriber.go`) — consumes domain events from JetStream, applies visibility rules, and publishes to NATS core subjects. This is transport-agnostic and needs no changes.
- **Streaming handlers** (`internal/api/mastodon/streaming.go`) — SSE-specific HTTP handlers that write `text/event-stream` responses.
- **Router** (`internal/api/router/router.go`, lines 164-180) — registers per-stream SSE endpoints with auth middleware.

### 1. Add WebSocket dependency

Add `github.com/coder/websocket` (formerly `nhooyr.io/websocket`) — a minimal, well-maintained WebSocket library that works with `net/http` handlers.

### 2. Create WebSocket handler

Add a new handler (e.g. in `internal/api/mastodon/streaming_ws.go`) that:

1. Accepts `GET /api/v1/streaming` with `Upgrade: websocket`
2. Authenticates via `access_token` query param (reuse `StreamingTokenFromQuery` middleware)
3. Upgrades the connection
4. Reads the initial `stream` query param to subscribe to the first stream
5. Reads incoming JSON messages to handle `subscribe`/`unsubscribe`
6. For each subscribed stream, calls `hub.Subscribe(streamKey)` and fans out events to the WebSocket as JSON
7. Handles connection close, ping/pong, and cleanup

### 3. Route registration

Add a route that handles the upgrade path. Options:
- Register a single `/api/v1/streaming` handler that checks for the `Upgrade` header and dispatches to WebSocket or returns 400
- Or use middleware to detect the upgrade before the existing SSE routes

### 4. Reuse the Hub

The Hub's `Subscribe` method already returns a channel of events — the WebSocket handler just needs to serialize them differently (JSON wrapper with `stream` array instead of SSE `event:` / `data:` lines). No changes to the Hub or Subscriber should be needed.

### 5. Multi-stream multiplexing

Unlike SSE (one stream per connection), WebSocket connections can subscribe to multiple streams. The handler needs to:
- Maintain a map of active stream subscriptions per connection
- Spawn a goroutine per subscription that reads from the Hub channel and writes to the WebSocket
- Handle `unsubscribe` messages by calling the cancel function returned by `hub.Subscribe`

### 6. Tests

- Unit tests for the WebSocket handler (subscribe, unsubscribe, event delivery, auth)
- Test that `Upgrade: websocket` on `/api/v1/streaming` upgrades correctly
- Test multi-stream multiplexing
- Test cleanup on connection close

## Out of scope

- Changing the existing SSE implementation
- Changes to the Hub or Subscriber internals
- The `stream` query param on SSE endpoints (those already work per-endpoint)

### PR DESCRIPTION
**Pull request by chairswithlegs**
Closes #29

### CODE REVIEW

File: internal/api/mastodon/streaming_ws.go [hunk 1]
```diff
@@ -0,0 +1,316 @@
...
+			continue
+		}
+
+		switch msg.Type {
+		case "subscribe":
+			h.wsHandleSubscribe(ctx, msg, account, subscriptions, outbox)
+		case "unsubscribe":
+			streamKey, _, err := h.resolveWSStreamKey(ctx, msg, account)
+			if err != nil {
+				continue
```
Comment (chairswithlegs) [inline internal/api/mastodon/streaming_ws.go]: Should log the error.

File: internal/api/mastodon/timelines.go [hunk 2]
```diff
@@ -271,31 +188,23 @@ func (h *TimelinesHandler) GETTag(w http.ResponseWriter, r *http.Request) {
...
+	out := enrichedStatusesToAPIModels(enriched, h.instanceDomain)
 	firstID, lastID := firstLastIDsFromEnriched(enriched)
 	if link := LinkHeader(AbsoluteRequestURL(r, h.instanceDomain), firstID, lastID); link != "" {
 		w.Header().Set("Link", link)
 	}
 	api.WriteJSON(w, http.StatusOK, out)
 }
 
+// enrichedStatusesToAPIModels converts a slice of EnrichedStatus to API models.
+func enrichedStatusesToAPIModels(enriched []service.EnrichedStatus, instanceDomain string) []apimodel.Status {
```
Comment (chairswithlegs) [inline internal/api/mastodon/timelines.go]: Since this is just a loop and a wrapper, I think it would make sense to move this to `apimodel`.
